import "./globals.css";
import { Heebo } from "next/font/google";
const heebo = Heebo({ subsets: ["latin"] });
export const metadata = {
  title: "Fixtura Content Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="h-full bg-gray-100">
      <link rel="icon" type="image/png" href="/favicon-32x32.png"></link>
      <body  className={`${heebo.className} h-full`}>
        {children}
      </body> 
    </html>
  );
}
