import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Fixtura Content Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="h-full bg-gray-100">
      <body  className={`${inter.className} h-full`}>
        {children}
      </body>
    </html>
  );
}
