// APIS
import { RenderCount } from "@/api/renders";
import { SelectedRenderStatsClient } from "../client/StatsGroup";

export async function SelectedRenderStats({ params }) {
  const Count = await RenderCount(params.render);

  //console.log(Count)
  const data = [
    {
      title: "Games tracked",
      stats: Count?.GameCount?.Total, 
      description:
        "Refers to the number of games analyised during this render period",
    },
    {
      title: "Games Upcoming ",
      stats: Count?.GameCount.Upcoming,
      description:
        "The number of games tracking for the next 7 days",
    },

    {
      title: "Games with Results",
      stats: Count?.GameCount.Results,
      description:
        "The number of potential games tracked with results",
    },
  ];

  return <SelectedRenderStatsClient data={data} />;
}

// "A Downloadable reffers to a Video or Image you can download and post on your website or social media account"
//"Articles reffer to all potential write ups generated by Fixtura, this includes Long form publications and tweets"